name: Python CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04 # Use a stable Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Correct Python version specified as a string

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show installed packages
        run: pip list

      - name: Run tests
        run: |
          pytest --cov=app tests/
        continue-on-error: false # Ensure workflow stops if tests fail for debugging

  docker:
    runs-on: ubuntu-22.04 # Explicit version ensures compatibility
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t your-docker-repo/event_manager:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push your-docker-repo/event_manager:latest
